"use client";

import "@/styles/exam-paper-document.css";
import { organization } from "@/constants/navigation";
import {
  estimateTimeAllowedMinutes,
  flattenQuestions,
  getQuestionAnswer,
} from "@/lib/exam-paper";
import { formatDisplayDate } from "@/lib/format-date";
import type { Assignment, GeneratedPaper } from "@/types/assignment";
import { ExamPaperSection } from "./exam-paper-section";

interface ExamPaperDocumentProps {
  assignment: Assignment;
  paper: GeneratedPaper;
  regeneratingSection: string | null;
  onRegenerateSection: (sectionTitle: string) => void;
}

export function ExamPaperDocument({
  assignment,
  paper,
  regeneratingSection,
  onRegenerateSection,
}: ExamPaperDocumentProps) {
  const flat = flattenQuestions(paper.sections);
  const numberByKey = new Map(
    flat.map(({ section, question, number }) => [
      `${section.title}-${question.text}`,
      number,
    ]),
  );
  const timeMinutes = estimateTimeAllowedMinutes(assignment.totalMarks);
  const dueDisplay = formatDisplayDate(assignment.dueDate);
  const schoolName =
    assignment.schoolName?.trim() || organization.defaultSchoolName;
  const className =
    assignment.className?.trim() || organization.defaultClassName;

  return (
    <article className="exam-paper-preview w-full min-w-0 overflow-hidden rounded-xl px-4 py-5 shadow-[0_2px_16px_rgba(0,0,0,0.08)] sm:rounded-2xl sm:px-6 sm:py-8 print:rounded-none print:shadow-none">
      <header className="exam-header">
        <h1 className="school-name">{schoolName}</h1>
        <div className="exam-meta-grid">
          <p>
            <span className="field-label">Subject:</span>
            <span className="field-value"> {assignment.subject}</span>
          </p>
          <p>
            <span className="field-label">Class:</span>
            <span className="field-value"> {className}</span>
          </p>
        </div>
      </header>

      <div className="exam-meta-row">
        <span>
          <span className="field-label">Time Allowed:</span>
          <span className="field-value"> {timeMinutes} minutes</span>
        </span>
        <span>
          <span className="field-label">Maximum Marks:</span>
          <span className="field-value"> {assignment.totalMarks}</span>
        </span>
      </div>

      <p className="compulsory-note">
        All questions are compulsory unless stated otherwise.
      </p>

      <div className="student-fields">
        <div className="student-row">
          <span className="student-cell">
            <span className="field-label">Name:</span>
            <span className="student-field-line student-field-line--name" />
          </span>
          <span className="student-cell">
            <span className="field-label">Roll No:</span>
            <span className="student-field-line student-field-line--roll" />
          </span>
        </div>
        <div className="student-row">
          <span className="student-cell">
            <span className="field-label">Class:</span>
            <span className="field-value">{className}</span>
          </span>
          <span className="student-cell">
            <span className="field-label">Section:</span>
            <span className="student-field-line student-field-line--section" />
          </span>
        </div>
      </div>

      {paper.sections.map((section) => (
        <ExamPaperSection
          key={section.title}
          section={section}
          numberByKey={numberByKey}
          isRegenerating={regeneratingSection === section.title}
          onRegenerate={onRegenerateSection}
        />
      ))}

      <p className="end-marker">End of Question Paper</p>

      <section className="answer-key">
        <h2 className="answer-key-title">Answer Key:</h2>
        <p className="answer-key-subtitle">Model answers for teacher reference</p>
        <ol className="answer-key-list">
          {flat.map(({ question, number }) => (
            <li key={number} className="answer-key-item" value={number}>
              {getQuestionAnswer(question)}
            </li>
          ))}
        </ol>
      </section>

      <p className="exam-footer print:hidden">
        Due: {dueDisplay} · Generated by VedaAI
      </p>
    </article>
  );
}
